# Generated by Django 5.1.3 on 2024-12-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_allergies_alter_userprofile_budget_and_more'),
    ]

    operations = [
    ]
