# Generated by Django 5.1.3 on 2024-12-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241201_1701'),
    ]

    operations = [
    ]
