# Generated by Django 5.1.3 on 2024-12-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20241201_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='allergies',
            new_name='diet',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dietary_needs',
            new_name='health_concerns',
        ),
    ]
