# Generated by Django 5.1.3 on 2024-12-04 04:34

import django.db.models.deletion
from django.db import migrations, models

def set_default_budget(apps, schema_editor):
    # Get models
    UserProfile = apps.get_model("users", "UserProfile")
    Budget = apps.get_model("users", "Budget")
    
    # Create a default budget
    default_budget, created = Budget.objects.get_or_create(
        name="Default Budget",
        min_value=0.00,
        max_value=100.00,
        description="Default budget for existing users"
    )
    
    # Assign the default budget to all user profiles with no budget
    UserProfile.objects.filter(budget__isnull=True).update(budget=default_budget)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_allergies_userprofile_diet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.budget'),
        ),
    ]
