# Generated by Django 5.1.3 on 2024-12-04 17:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_budget_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
