# Generated by Django 5.1.3 on 2024-12-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_nutrition_tag_remove_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
